# Generated by Django 5.0 on 2023-12-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
