# Generated by Django 5.0 on 2023-12-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
